import * as process from 'process';

export const environmentVariablesDevelopment = {
  ETHANG_SANITY_DATASET: process.env['ETHANG_SANITY_DATASET'],
  ETHANG_SANITY_EDITOR_TOKEN: process.env['ETHANG_SANITY_EDITOR_TOKEN'],
  ETHANG_SANITY_PROJECT_ID: process.env['ETHANG_SANITY_PROJECT_ID'],
  ETHANG_SANITY_VIEWER_TOKEN: process.env['ETHANG_SANITY_VIEWER_TOKEN'],
  MODE: 'production',
  NEXT_PUBLIC_STERETT_SANITY_DATASET:
    process.env['NEXT_PUBLIC_STERETT_SANITY_DATASET'],
  NEXT_PUBLIC_STERETT_SANITY_PROJECT_ID:
    process.env['NEXT_PUBLIC_STERETT_SANITY_PROJECT_ID'],
  NEXT_PUBLIC_STERETT_SANITY_RO_TOKEN:
    process.env['NEXT_PUBLIC_STERETT_SANITY_RO_TOKEN'],
  STERETT_SANITY_ADMIN_TOKEN: process.env['STERETT_SANITY_ADMIN_TOKEN'],
};
